# Generated by Django 4.0.4 on 2022-06-11 02:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_event_table_participation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('sharer', 'event')},
        ),
    ]
