# Generated by Django 4.0.4 on 2022-06-11 02:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_participation_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='sharer',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'event')},
        ),
    ]
