# Generated by Django 4.0.4 on 2022-06-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
