# Generated by Django 4.0.4 on 2022-06-13 01:08

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_users_event_participants_event_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', django.db.models.expressions.F('start_time'))), name='endtime_CHK'),
        ),
    ]
